name: marine_aqua_technologies
description: MARINE AQUA TECHNOLOGIES - Smart Aquaculture. Better Results.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/products/
    - assets/
    - assets/success_stories/
    - assets/success_stories/thumbs/
