import 'package:flutter/material.dart';

const blue = Color(0xFF075985);
const cyan = Color(0xFF129BCB);
const bg = Color(0xFFF4FAFD);
const pale = Color(0xFFE5F6FC);

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(const MarineAquaApp());
}

class MarineAquaApp extends StatelessWidget {
  const MarineAquaApp({super.key});
  @override
  Widget build(BuildContext context) => MaterialApp(
        debugShowCheckedModeBanner: false,
        title: 'Marine Aqua Technologies',
        theme: ThemeData(useMaterial3: true, scaffoldBackgroundColor: bg,
            colorScheme: ColorScheme.fromSeed(seedColor: blue)),
        home: const SplashScreen(),
      );
}

class SplashScreen extends StatefulWidget {
  const SplashScreen({super.key});
  @override State<SplashScreen> createState() => _SplashState();
}
class _SplashState extends State<SplashScreen> {
  @override void initState() { super.initState(); Future.delayed(const Duration(seconds: 2), () {
    if (mounted) Navigator.pushReplacement(context, MaterialPageRoute(builder: (_) => const LoginScreen()));
  }); }
  @override Widget build(BuildContext context) => Scaffold(backgroundColor: Colors.white,
    body: Center(child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [
      Img('assets/products/marine logo.png', 170, 170),
      const SizedBox(height: 22),
      const Text('ఆక్వా సాగులో ప్రతి దశలో... మీకు తోడుగా', textAlign: TextAlign.center,
        style: TextStyle(color: blue,fontSize:18,fontWeight:FontWeight.bold)),
      const SizedBox(height:10), const Text('MARINE AQUA TECHNOLOGIES',style:TextStyle(color:blue,fontSize:17,fontWeight:FontWeight.w800)),
      const SizedBox(height:28), const CircularProgressIndicator(color:cyan),
    ])));
}

class LoginScreen extends StatefulWidget { const LoginScreen({super.key}); @override State<LoginScreen> createState()=>_LoginState(); }
class _LoginState extends State<LoginScreen> {
  final c=TextEditingController();
  @override void dispose(){c.dispose();super.dispose();}
  void send(){final n=c.text.trim(); if(n.length!=10 || int.tryParse(n)==null){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('సరైన 10-digit mobile number నమోదు చేయండి')));return;}
    Navigator.push(context,MaterialPageRoute(builder:(_)=>OtpScreen(mobile:n)));}
  @override Widget build(BuildContext context)=>Scaffold(backgroundColor:Colors.white,body:SafeArea(child:SingleChildScrollView(padding:const EdgeInsets.all(28),child:Column(children:[
    const SizedBox(height:20), Img('assets/products/marine logo.png',140,140), const SizedBox(height:15),
    const Text('MARINE AQUA TECHNOLOGIES',textAlign:TextAlign.center,style:TextStyle(color:blue,fontSize:23,fontWeight:FontWeight.w900)),
    const SizedBox(height:8),const Text('ఆక్వా సాగులో ప్రతి దశలో... మీకు తోడుగా',textAlign:TextAlign.center,style:TextStyle(color:blue,fontWeight:FontWeight.w600)),
    const SizedBox(height:55),const Align(alignment:Alignment.centerLeft,child:Text('Mobile Login',style:TextStyle(color:blue,fontSize:28,fontWeight:FontWeight.w900))),
    const SizedBox(height:8),const Align(alignment:Alignment.centerLeft,child:Text('Enter your mobile number to continue',style:TextStyle(color:Colors.grey))),
    const SizedBox(height:22),TextField(controller:c,keyboardType:TextInputType.phone,maxLength:10,decoration:InputDecoration(counterText:'',prefixText:'+91  ',hintText:'Mobile number',filled:true,fillColor:bg,border:OutlineInputBorder(borderRadius:BorderRadius.circular(18)),focusedBorder:OutlineInputBorder(borderRadius:BorderRadius.circular(18),borderSide:const BorderSide(color:cyan,width:2)))),
    const SizedBox(height:20),SizedBox(width:double.infinity,height:55,child:ElevatedButton(onPressed:send,style:ElevatedButton.styleFrom(backgroundColor:blue,foregroundColor:Colors.white,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(18))),child:const Text('SEND OTP',style:TextStyle(fontWeight:FontWeight.bold,fontSize:17)))),
  ]))));
}

class OtpScreen extends StatefulWidget { final String mobile; const OtpScreen({super.key,required this.mobile}); @override State<OtpScreen> createState()=>_OtpState(); }
class _OtpState extends State<OtpScreen>{ final c=TextEditingController(); @override void dispose(){c.dispose();super.dispose();}
  void verify(){if(c.text.trim()!='123456'){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Test OTP: 123456')));return;} Navigator.pushAndRemoveUntil(context,MaterialPageRoute(builder:(_)=>const MainNav()),(_)=>false);}
  @override Widget build(BuildContext context)=>Scaffold(backgroundColor:Colors.white,body:SafeArea(child:SingleChildScrollView(padding:const EdgeInsets.all(28),child:Column(children:[
    Align(alignment:Alignment.centerLeft,child:IconButton(onPressed:()=>Navigator.pop(context),icon:const Icon(Icons.arrow_back))),Img('assets/products/marine logo.png',120,120),const SizedBox(height:15),
    const Text('Verify OTP',style:TextStyle(color:blue,fontSize:30,fontWeight:FontWeight.bold)),const SizedBox(height:8),Text('Enter the 6-digit OTP sent to\n+91 ${widget.mobile}',textAlign:TextAlign.center,style:const TextStyle(color:Colors.grey,fontSize:16)),const SizedBox(height:30),
    TextField(controller:c,keyboardType:TextInputType.number,maxLength:6,textAlign:TextAlign.center,style:const TextStyle(fontSize:25,letterSpacing:8,fontWeight:FontWeight.bold),decoration:InputDecoration(counterText:'',hintText:'Enter 6-digit OTP',filled:true,fillColor:bg,border:OutlineInputBorder(borderRadius:BorderRadius.circular(18)))),
    const SizedBox(height:18),SizedBox(width:double.infinity,height:55,child:ElevatedButton(onPressed:verify,style:ElevatedButton.styleFrom(backgroundColor:blue,foregroundColor:Colors.white),child:const Text('VERIFY & CONTINUE',style:TextStyle(fontWeight:FontWeight.bold)))),const SizedBox(height:15),const Text('DEMO OTP: 123456',style:TextStyle(color:cyan,fontWeight:FontWeight.bold))
  ]))));
}

class MainNav extends StatefulWidget { const MainNav({super.key}); @override State<MainNav> createState()=>_MainNavState(); }
class _MainNavState extends State<MainNav>{int i=0;final pages=const[HomeScreen(),ProductsScreen(),PondsScreen(),SupportScreen(),ProfileScreen()];
 @override Widget build(BuildContext context)=>Scaffold(body:IndexedStack(index:i,children:pages),bottomNavigationBar:NavigationBar(selectedIndex:i,backgroundColor:Colors.white,indicatorColor:const Color(0xFFD5F3FC),onDestinationSelected:(v)=>setState(()=>i=v),destinations:const[
  NavigationDestination(icon:Icon(Icons.home_outlined),selectedIcon:Icon(Icons.home),label:'Home'),NavigationDestination(icon:Icon(Icons.inventory_2_outlined),selectedIcon:Icon(Icons.inventory_2),label:'Products'),NavigationDestination(icon:Icon(Icons.water_outlined),selectedIcon:Icon(Icons.water),label:'My Ponds'),NavigationDestination(icon:Icon(Icons.headset_mic_outlined),selectedIcon:Icon(Icons.headset_mic),label:'Support'),NavigationDestination(icon:Icon(Icons.person_outline),selectedIcon:Icon(Icons.person),label:'Profile') ]));}

class HomeScreen extends StatelessWidget{const HomeScreen({super.key});
 @override Widget build(BuildContext context)=>SafeArea(child:CustomScrollView(slivers:[SliverToBoxAdapter(child:header()),SliverToBoxAdapter(child:hero(context)),SliverToBoxAdapter(child:quick()),SliverToBoxAdapter(child:dealer()),SliverToBoxAdapter(child:title('Our Aquaculture Solutions')),SliverToBoxAdapter(child:homeProducts()),SliverToBoxAdapter(child:title('Success Stories')),SliverToBoxAdapter(child:stories()),SliverToBoxAdapter(child:waterTools()),SliverToBoxAdapter(child:guides()),const SliverToBoxAdapter(child:SizedBox(height:20))]));
 Widget header()=>Padding(padding:const EdgeInsets.fromLTRB(16,10,12,10),child:Row(children:[Img('assets/products/marine logo.png',62,62),const SizedBox(width:10),const Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('MARINE AQUA',style:TextStyle(color:blue,fontSize:21,fontWeight:FontWeight.w900)),Text('TECHNOLOGIES',style:TextStyle(color:blue,fontSize:20,fontWeight:FontWeight.w900)),Text('Smart Aquaculture. Better Results.',style:TextStyle(color:blue,fontSize:10))])),IconButton(onPressed:(){},icon:const Icon(Icons.notifications_none,color:blue)),IconButton(onPressed:(){},icon:const Icon(Icons.translate,color:blue)),const CircleAvatar(backgroundColor:pale,child:Icon(Icons.person,color:blue))]));
 Widget hero(BuildContext c)=>Padding(padding:const EdgeInsets.all(16),child:Container(height:190,decoration:BoxDecoration(borderRadius:BorderRadius.circular(24),gradient:const LinearGradient(colors:[Color(0xFF064E7A),cyan])),clipBehavior:Clip.antiAlias,child:Stack(children:[Positioned.fill(child:Image.asset('assets/products/hero_shrimp.jpg',fit:BoxFit.cover,opacity:const AlwaysStoppedAnimation(.32),errorBuilder:(_,__,___)=>const SizedBox())),Padding(padding:const EdgeInsets.all(20),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Healthy Ponds\nStronger Shrimp\nHigher Profits',style:TextStyle(color:Colors.white,fontSize:26,fontWeight:FontWeight.w900,height:1.03)),const SizedBox(height:9),const Text('Complete Aquaculture Solutions\nfor a Better Tomorrow',style:TextStyle(color:Colors.white,fontSize:13)),const Spacer(),ElevatedButton.icon(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const ProductsScreen())),icon:const Icon(Icons.arrow_forward),label:const Text('Explore Products'),style:ElevatedButton.styleFrom(backgroundColor:Colors.white,foregroundColor:blue))]))])));
 Widget quick(){final x=[['Tip Of The Day','Maintain proper dissolved oxygen levels for better growth.',Icons.lightbulb_outline,const Color(0xFFDDF7E8)],['Shrimp Culture Guide','Learn setup, management & best practices.',Icons.menu_book_outlined,const Color(0xFFDDF0FF)],['Biomass Calculator','Get estimated biomass in 3 easy steps.',Icons.calculate_outlined,const Color(0xFFDDF7E8)],['Shrimp Diseases','Identify, prevent & manage common diseases.',Icons.health_and_safety_outlined,const Color(0xFFFFE1E1)]];return Padding(padding:const EdgeInsets.symmetric(horizontal:16),child:GridView.builder(shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),itemCount:4,gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:2,crossAxisSpacing:12,mainAxisSpacing:12,childAspectRatio:1.18),itemBuilder:(_,i)=>Container(padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:x[i][3] as Color,borderRadius:BorderRadius.circular(20)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(x[i][2] as IconData,color:i==3?Colors.red:Colors.blue,size:32),const SizedBox(height:7),Text(x[i][0] as String,maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(color:blue,fontSize:16,fontWeight:FontWeight.w800)),const SizedBox(height:4),Expanded(child:Text(x[i][1] as String,maxLines:3,overflow:TextOverflow.ellipsis,style:const TextStyle(color:Color(0xFF52708A),fontSize:12))),const Align(alignment:Alignment.bottomRight,child:Icon(Icons.arrow_forward,color:blue))]))));}
 Widget dealer()=>Padding(padding:const EdgeInsets.fromLTRB(16,18,16,8),child:Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:const Color(0xFFE1F3FF),borderRadius:BorderRadius.circular(22)),child:Row(children:[const CircleAvatar(radius:32,backgroundColor:Colors.white,child:Icon(Icons.location_on,color:Colors.red,size:42)),const SizedBox(width:12),const Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Dealers Location',style:TextStyle(color:blue,fontSize:20,fontWeight:FontWeight.w800)),Text('Find our nearest dealers across India',style:TextStyle(color:Color(0xFF52708A),fontSize:12))])),ElevatedButton(onPressed:(){},child:const Text('Find Nearby'))]));
 Widget title(String s)=>Padding(padding:const EdgeInsets.fromLTRB(18,16,18,10),child:Row(children:[Expanded(child:Text(s,style:const TextStyle(color:blue,fontSize:22,fontWeight:FontWeight.w900))),const Text('View All →',style:TextStyle(color:Color(0xFF1689D7),fontWeight:FontWeight.bold))]));
 Widget homeProducts(){final p=ProductsScreen.products.take(5).toList();return SizedBox(height:175,child:ListView.separated(padding:const EdgeInsets.symmetric(horizontal:16),scrollDirection:Axis.horizontal,itemCount:p.length,separatorBuilder:(_,__)=>const SizedBox(width:10),itemBuilder:(_,i)=>Container(width:145,padding:const EdgeInsets.all(9),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(18)),child:Column(children:[Expanded(child:Img(p[i]['image']!,120,120)),Text(p[i]['name']!,maxLines:2,textAlign:TextAlign.center,overflow:TextOverflow.ellipsis,style:const TextStyle(color:blue,fontWeight:FontWeight.w800,fontSize:13))]))));}
 Widget stories()=>SizedBox(height:155,child:ListView.separated(padding:const EdgeInsets.symmetric(horizontal:16),scrollDirection:Axis.horizontal,itemCount:2,separatorBuilder:(_,__)=>const SizedBox(width:12),itemBuilder:(_,i)=>Container(width:300,decoration:BoxDecoration(borderRadius:BorderRadius.circular(20),color:blue),clipBehavior:Clip.antiAlias,child:Stack(fit:StackFit.expand,children:[Image.asset(i==0?'assets/products/hero_shrimp.jpg':'assets/products/shrimp_guide.png',fit:BoxFit.cover,opacity:const AlwaysStoppedAnimation(.65),errorBuilder:(_,__,___)=>const SizedBox()),Positioned(left:14,bottom:12,child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Icon(Icons.play_circle_outline,color:Colors.white,size:35),Text(i==0?'40% Faster Growth':'Better Survival Rate',style:const TextStyle(color:Colors.white,fontWeight:FontWeight.w900,fontSize:17)),Text(i==0?'West Godavari, AP':'Krishna, AP',style:const TextStyle(color:Colors.white,fontSize:12))]))])));
 Widget waterTools()=>Padding(padding:const EdgeInsets.all(16),child:Container(padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:const Color(0xFFDDF8E8),borderRadius:BorderRadius.circular(22)),child:Column(children:[const Align(alignment:Alignment.centerLeft,child:Text('🧪  Water Quality Tools',style:TextStyle(color:blue,fontSize:21,fontWeight:FontWeight.w900))),const SizedBox(height:10),Row(children:['pH','Temperature','Salinity','DO'].map((s)=>Expanded(child:Container(margin:const EdgeInsets.all(3),padding:const EdgeInsets.symmetric(vertical:14),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(15)),child:Text(s,textAlign:TextAlign.center,style:const TextStyle(color:blue,fontWeight:FontWeight.bold)))).toList())])));
 Widget guides()=>Padding(padding:const EdgeInsets.fromLTRB(16,4,16,0),child:Column(children:[const Align(alignment:Alignment.centerLeft,child:Text('📖  Shrimp Growth Guide',style:TextStyle(color:blue,fontSize:21,fontWeight:FontWeight.w900))),const SizedBox(height:10),SizedBox(height:135,child:ListView.separated(scrollDirection:Axis.horizontal,itemCount:4,separatorBuilder:(_,__)=>const SizedBox(width:10),itemBuilder:(_,i)=>SizedBox(width:180,child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[ClipRRect(borderRadius:BorderRadius.circular(14),child:Img(i==0?'assets/products/shrimp_guide.png':'assets/products/hero_shrimp.jpg',180,85)),Text(['PL Selection','Pond Preparation','Feeding Guide','Moulting Care'][i],style:const TextStyle(color:blue,fontWeight:FontWeight.bold)),Text(['Choose healthy PL','Get your pond ready','Right feed, faster growth','Stronger shell, better growth'][i],style:const TextStyle(color:Color(0xFF52708A),fontSize:10))])))]));
}

class ProductsScreen extends StatelessWidget{const ProductsScreen({super.key});static const products=<Map<String,String>>[
 {'name':'Marine 6G','image':'assets/products/marine 6g.png'}, {'name':'Marine Volt-X','image':'assets/products/marine volt-x.png'}, {'name':'Bio Sludge-X','image':'assets/products/Bio sludge.png'}, {'name':'Marine ProTab','image':'assets/products/marine protab.png'}, {'name':'Marine Vibrio Shield','image':'assets/products/Marine vibrio shield.png'}, {'name':'Marine White Shield','image':'assets/products/marine white shield.png'}, {'name':'Free Moult','image':'assets/products/Free moult.png'}, {'name':'Red Thunder','image':'assets/products/Red thunder.png'}, {'name':'Starmin','image':'assets/products/Starmin.png'}, {'name':'Yucca Pro','image':'assets/products/Yucca Pro.png'}, {'name':'Zeoneem','image':'assets/products/Zeoneem.png'}, {'name':'Chlorides','image':'assets/products/chlorides.png'}, {'name':'Nutrimin','image':'assets/products/nutrimin.png'}, {'name':'OXYTAB Plus','image':'assets/products/oxytab plus.png'}, {'name':'Bio Soil','image':'assets/products/Bio soil.png'}, {'name':'Hi-Soft','image':'assets/products/Hi-Soft.png'}];
 @override Widget build(BuildContext context)=>SafeArea(child:CustomScrollView(slivers:[const SliverToBoxAdapter(child:Padding(padding:EdgeInsets.fromLTRB(20,20,20,14),child:Text('Our Products',style:TextStyle(color:blue,fontSize:29,fontWeight:FontWeight.w900)))),SliverPadding(padding:const EdgeInsets.all(16),sliver:SliverGrid(delegate:SliverChildBuilderDelegate((_,i)=>ProductCard(products[i]),childCount:products.length),gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:2,crossAxisSpacing:12,mainAxisSpacing:12,childAspectRatio:.78))) ]));}
class ProductCard extends StatelessWidget{final Map<String,String> p;const ProductCard(this.p,{super.key});@override Widget build(BuildContext context)=>InkWell(onTap:()=>showModalBottomSheet(context:context,showDragHandle:true,builder:(_)=>Padding(padding:const EdgeInsets.all(25),child:Column(mainAxisSize:MainAxisSize.min,children:[SizedBox(height:190,child:Img(p['image']!,190,190)),Text(p['name']!,style:const TextStyle(color:blue,fontSize:22,fontWeight:FontWeight.w900)),const SizedBox(height:8),const Text('Product details, benefits, composition and dosage can be added here.',textAlign:TextAlign.center),const SizedBox(height:20)]))),child:Container(padding:const EdgeInsets.all(9),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(24),border:Border.all(color:const Color(0xFFE1EDF2))),child:Column(children:[Expanded(child:Img(p['image']!,160,180)),Text(p['name']!,maxLines:2,textAlign:TextAlign.center,overflow:TextOverflow.ellipsis,style:const TextStyle(color:Color(0xFF087B9E),fontSize:16,fontWeight:FontWeight.w900))])));}

class PondsScreen extends StatelessWidget{const PondsScreen({super.key});@override Widget build(BuildContext context)=>const SimplePage(title:'My Ponds',icon:Icons.water,text:'Add your pond details to monitor aquaculture activity.');}
class SupportScreen extends StatelessWidget{const SupportScreen({super.key});@override Widget build(BuildContext context)=>const SimplePage(title:'Support',icon:Icons.headset_mic,text:'Get help from the Marine Aqua Technologies technical team.');}
class ProfileScreen extends StatelessWidget{const ProfileScreen({super.key});@override Widget build(BuildContext context)=>SafeArea(child:SingleChildScrollView(padding:const EdgeInsets.all(20),child:Column(children:[const CircleAvatar(radius:45,backgroundColor:pale,child:Icon(Icons.person,size:55,color:blue)),const SizedBox(height:12),const Text('Marine Aqua User',style:TextStyle(color:blue,fontSize:23,fontWeight:FontWeight.w900)),const SizedBox(height:20),...['Personal Details','Notifications','Language','Privacy','About Marine Aqua'].map((s)=>Card(child:ListTile(leading:const Icon(Icons.person_outline,color:blue),title:Text(s),trailing:const Icon(Icons.arrow_forward_ios,size:16)))),const SizedBox(height:15),OutlinedButton.icon(onPressed:(){Navigator.pushAndRemoveUntil(context,MaterialPageRoute(builder:(_)=>const LoginScreen()),(_)=>false);},icon:const Icon(Icons.logout),label:const Text('Logout'))])));}
class SimplePage extends StatelessWidget{final String title,text;final IconData icon;const SimplePage({super.key,required this.title,required this.icon,required this.text});@override Widget build(BuildContext context)=>SafeArea(child:Padding(padding:const EdgeInsets.all(20),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:const TextStyle(color:blue,fontSize:29,fontWeight:FontWeight.w900)),const SizedBox(height:20),Container(width:double.infinity,padding:const EdgeInsets.all(25),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(22)),child:Column(children:[Icon(icon,size:60,color:cyan),const SizedBox(height:15),Text(text,textAlign:TextAlign.center,style:const TextStyle(color:Color(0xFF52708A),fontSize:15))]))])));}

class Img extends StatelessWidget{final String path;final double w,h;const Img(this.path,this.w,this.h,{super.key});@override Widget build(BuildContext context)=>Image.asset(path,width:w,height:h,fit:BoxFit.contain,errorBuilder:(_,__,___)=>Container(width:w,height:h,alignment:Alignment.center,child:const Icon(Icons.image_not_supported_outlined,color:Colors.grey,size:42)));}
